import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Link from "next/link";

import { DynamicNav } from "@/components/site/dynamic-nav";

const font = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased max-w-7xl mx-auto`}>
        <Nav />
        <main className="border-x border-b">{children}</main>
      </body>
    </html>
  );
}

const Nav = () => {
  return (
    <nav className="uppercase">
      <section className="border-x sticky top-0 font-medium border-t p-3 flex justify-between items-center bg-accent/30 backdrop-blur-md">
        <Link href="/">Blocks.is ◾</Link>
        <div className="underline underline-offset-2 flex gap-3">
          <a href="https://github.com/brijr/blocks">GitHub</a>
          <a href="https://x.com/bridgertower">Follow for Updates</a>
        </div>
      </section>
      <DynamicNav />
    </nav>
  );
};
